# Generated by Django 3.1 on 2021-07-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_trending',
        ),
    ]
