# Generated by Django 3.1 on 2021-08-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
