# Generated by Django 3.1 on 2021-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210827_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
